### ISSUE TITLE
Namespace Issue

### ISSUE THREAD

**Issue by jguo144** [AppGeo/ckanext-agsview#5]
There is a namespace issue if you install this extension along with [ckanext-spatial.](https://github.com/ckan/ckanext-spatial)
Both extensions have a file that's labeled the same "public/js/common_map.js".

**Comment by calvinmetcalf** [comment]
i wonder if this is the issue or just we are providing conflicting commonLeafletMap functions in there

**Comment by GuidoS** [comment]
@jguo144 a new pull request was merged and @calvinmetcalf changed the leaflet function name. Please try this out with the new commit.

**Comment by jguo144** [comment]
Changing the leaflet function name and renaming common_map.js to ags_common_map.js fixed the issue.
