### ISSUE TITLE
Mixed Content Warning

### ISSUE THREAD

**Issue by jqnatividad** [AppGeo/ckanext-agsview#8]
Was able to use a Proxy to serve up the this info

https://jqnatividad-prod.apigee.net/mapservices-bostonredevelopmentauthority-org/arcgis/rest/services/Maps/Zoning/MapServer/0

from 

http://mapservices.bostonredevelopmentauthority.org/arcgis/rest/services/Maps/Zoning/MapServer/0

However, there is still mixed content warning from ags_fs_view/ags_ms_view js loading http://epsg.io.

https://github.com/AppGeo/ckanext-agsview/blob/master/ckanext/agsview/public/js/ags_fs_view.js#L72

https://github.com/AppGeo/ckanext-agsview/blob/master/ckanext/agsview/public/js/ags_ms_view.js#L106

See https://data.boston.gov/dataset/zoning-districts/resource/d993c51f-0224-429e-81c1-d71e1b507b5e

cc @calvinmetcalf @GuidoS  @pgirard @jguo144 @samibaig

**Comment by klokan** [comment]
Do you know we serve the epsg.io web over https:// as well?
https://epsg.io/

**Comment by calvinmetcalf** [comment]
thanks @klokan pushed up a fix

**Comment by jqnatividad** [comment]
We applied the fixes and the map partly renders, however, we now have another set of JS errors

https://data.boston.gov/dataset/zoning-districts/resource/d993c51f-0224-429e-81c1-d71e1b507b5e

cc @pgirard @calvinmetcalf @GuidoS

**Comment by calvinmetcalf** [comment]
it works for me, I do see 2 warnings in the console but those arn't related
to our plugin
